# Generated by Django 6.0 on 2025-12-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_bio_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
