# Generated by Django 6.0 on 2025-12-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
