# Generated by Django 6.0 on 2025-12-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_allergies_alter_profile_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_information',
            field=models.TextField(blank=True),
        ),
    ]
