# Generated by Django 6.0 on 2025-12-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_extra_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_preferences',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
