# Generated by Django 6.0 on 2026-01-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_activity_level_alter_profile_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_preferences',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
